[frontends.tcp_1337]
listen_addr = "0.0.0.0:1337"
backend = "tcp3000_out"

[backends.tcp3000_out]
  [backends.tcp3000_out.servers]
    [backends.tcp3000_out.servers.server1]
    addr = "127.0.0.1:8080"
    [backends.tcp3000_out.servers.server2]
    addr = "127.0.0.1:8081"

